### ISSUE TITLE
When re-entering the archive, items may be deleted

### ISSUE THREAD

**Issue by chilianer** [AndreyMrovol/LethalItemsDeclutter#1]
When the total value of remaining scrap items on my spaceship exceeds ten thousand, upon re-entering the archive, the quantity of waste will be reduced to the extent that the value is only left with nine thousand

**Comment by chilianer** [comment]
Thank you for your guidance. I forgot to add 'moreitem' when organizing the new package.
How foolish I am

**Comment by AndreyMrovol** [comment]
Don't worry, it happens.
