### ISSUE TITLE
This mod still being developed?

### ISSUE THREAD

**Issue by KleskReaver** [AndreyMrovol/LethalItemsDeclutter#4]
After checking out this mod and realising how I could use it to make the ship cupboard actually work and nice to look at, I would like to put some serious effort into putting all the items into the configs, but I'd like to know first if you are still developing this mod :)

**Comment by AndreyMrovol** [comment]
Hey, I'm planning to do a rewrite of this mod (so it's working on latest versions), but sadly I'm unable to give you an ETA 🥲

**Comment by KleskReaver** [comment]
Thanks! Looking forward to the update :)
